version: '3'
services:
  backend:
    build:
      context: /var/lib/jenkins/workspace/Backend/
      dockerfile: Dockerfile-backend
    ports:
      - 8087:8087
    volumes:
      - ./application.properties:/app/config/application.properties
    environment:
      COMPOSE_HTTP_TIMEOUT: 120

  frontend:
    build:
      context: /var/lib/jenkins/workspace/Frontend-Angular/
      dockerfile: Dockerfile-frontend
    ports:
      - 4200:80
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./magasin-nginx-custom.conf:/etc/nginx/conf.d/default.conf
    restart: always

