// export class Twhinh200 {
//     //id!: number;
//     tOorg!: number;
//     tOrno!: string;
//     tOset!: number;
//     tSeri!: string;
//     tIttp!: number;
//     tOdat!: Date;
//     tSfty!: number;
//     tSfco!: string;
//     tStty!: number;
//     tStco!: string;
//     tSfcp!: number;
//     tStcp!: number;
//     tSfad!: string;
//     tStad!: string;
//     tSfit!: string;
//     tStit!: string;
//     tSfrv!: string;
//     tStrv!: string;
//     tSflo!: string;
//     tStlo!: string;
//     tOtyp!: string;
//     tDepc!: number;
//     tWdep!: string;
//     tBlor!: number;
//     tRtrn!: number;
//     tCons!: number;
//     tInvc!: number;
//     tBflh!: number;
//     tRrgd!: number;
//     tDmst!: number;
//     tCarr!: string;
//     tCbin!: number;
//     tCrte!: string;
//     tCdec!: string;
//     tPtpa!: string;
//     tMotv!: string;
//     tDelc!: string;
//     tServ!: string;
//     tPddt!: Date;
//     tPrdt!: Date;
//     tMint!: number;
//     tMaxt!: number;
//     tMind!: number;
//     tMaxd!: number;
//     tClan!: string;
//     tGrid!: string;
//     tSetn!: number;
//     tInfo!: string;
//     tRefe!: string;
//     tIsit!: number;
//     tRodr!: string;
//     tAkit!: string;
//     tCtdt!: Date;
//     tAdat!: Date;
//     tClgr!: string;
//     tList!: string;
//     tItem!: string;
//     tQoro!: number;
//     tOrun!: string;
//     tQord!: number;
//     tAsst!: number;
//     tTxta!: number;
//     tTxtb!: number;
//     tRefcntd!: number;
//     tRefcntu!: number;
//     tHsta!: number;
//  }
// export class Twhinh200 {
//     tOorg!: number;
//     tOrno!: string;
//     tOset!: number;
//     tSeri!: string;
//     tIttp!: number;
//     tOdat!: Date;
//     tSfty!: number;
//     tSfco!: string;
//     tStty!: number;
//     tStco!: string;
//     tSfcp!: number;
//     tStcp!: number;
//     tSfad!: string;
//     tStad!: string;
//     tSfit!: string;
//     tStit!: string;
//     tSfrv!: string;
//     tStrv!: string;
//     tSflo!: string;
//     tStlo!: string;
//     tOtyp!: string;
//     tDepc!: number;
//     tWdep!: string;
//     tBlor!: number;
//     tRtrn!: number;
//     tCons!: number;
//     tInvc!: number;
//     tBflh!: number;
//     tRrgd!: number;
//     tDmst!: number;
//     tCarr!: string;
//     tCbin!: number;
//     tCrte!: string;
//     tCdec!: string;
//     tPtpa!: string;
//     tMotv!: string;
//     tDelc!: string;
//     tServ!: string;
//     tPddt!: Date;
//     tPrdt!: Date;
//     tMint!: number;
//     tMaxt!: number;
//     tMind!: number;
//     tMaxd!: number;
//     tClan!: string;
//     tGrid!: string;
//     tSetn!: number;
//     tInfo!: string;
//     tRefe!: string;
//     tIsit!: number;
//     tRodr!: string;
//     tAkit!: string;
//     tCtdt!: Date;
//     tAdat!: Date;
//     tClgr!: string;
//     tList!: string;
//     tItem!: string;
//     tQoro!: number;
//     tOrun!: string;
//     tQord!: number;
//     tAsst!: number;
//     tTxta!: number;
//     tTxtb!: number;
//     tRefcntd!: number;
//     tRefcntu!: number;
//     tHsta!: number;
//   }
export class Twhinh200 {
  toorg!: number;
  torno!: string;
  toset!: number;
  tseri!: string;
  tittp!: number;
  todat!: Date;
  tsfty!: number;
  tsfco!: string;
  tstty!: number;
  tstco!: string;
  tsfcp!: number;
  tstcp!: number;
  tsfad!: string;
  tstad!: string;
  tsfit!: string;
  tstit!: string;
  tsfrv!: string;
  tstrv!: string;
  tsflo!: string;
  tstlo!: string;
  totyp!: string;
  tdepc!: number;
  twdep!: string;
  tblor!: number;
  trtrn!: number;
  tcons!: number;
  tinvc!: number;
  tbflh!: number;
  trrgd!: number;
  tdmst!: number;
  tcarr!: string;
  tcbin!: number;
  tcrte!: string;
  tcdec!: string;
  tptpa!: string;
  tmotv!: string;
  tdelc!: string;
  tserv!: string;
  tpddt!: Date;
  tprdt!: Date;
  tmint!: number;
  tmaxt!: number;
  tmind!: number;
  tmaxd!: number;
  tclan!: string;
  tgrid!: string;
  tsetn!: number;
  tinfo!: string;
  trefe!: string;
  tisit!: number;
  trodr!: string;
  takit!: string;
  tctdt!: Date;
  tadat!: Date;
  tclgr!: string;
  tlist!: string;
  titem!: string;
  tqoro!: number;
  tqrun!: string;
  tqord!: number;
  tasst!: number;
  ttxta!: number;
  ttxtb!: number;
  trefcntd!: number;
  trefcntu!: number;
  thsta!: number;
}
