// export class Twhinh220 {
//    // id!: number;
//     tOorg!: number;
//     tOrno!: string;
//     tPono!: number;
//     tSeqn!: number;
//     tOset!: number;
//     tCwar!: string;
//     tComp!: number;
//     tAcvt!: number;
//     tItem!: string;
//     tSerl!: string;
//     tSsts!: number;
//     tLsel!: number;
//     tClot!: string;
//     tEffn!: number;
//     tRevi!: string;
//     tPrio!: number;
//     tQoro!: number;
//     tOrun!: string;
//     tUbin!: number;
//     tHstq!: number;
//     tQord!: number;
//     tQadv!: number;
//     tQrel!: number;
//     tQpic!: number;
//     tQapr!: number;
//     tQrej!: number;
//     tQnse!: number;
//     tQnsh!: number;
//     tQshp!: number;
//     tQoor!: number;
//     tQova!: number;
//     tQovd!: number;
//     tQcnl!: number;
//     tPddt!: Date;
//     tPrdt!: Date;
//     tAddt!: Date;
//     tInup!: number;
//     tBflh!: number;
//     tRush!: number;
//     tCdck!: number;
//     tQreq!: number;
//     tQcad!: number;
//     tQact!: number;
//     tShrt!: number;
//     tBlck!: number;
//     tCncl!: number;
//     tBcko!: number;
//     tPkdf!: string;
//     tIubw!: number;
//     tGefo!: number;
//     tFmor!: string;
//     tFmln!: number;
//     tOvlp!: number;
//     tUwop!: number;
//     tOrpr!: number;
//     tOcur!: string;
//     tCsvl!: number;
//     tCsvc!: string;
//     tFprj!: string;
//     tFspa!: string;
//     tFact!: string;
//     tFstl!: string;
//     tFcco!: string;
//     tTprj!: string;
//     tTspa!: string;
//     tTact!: string;
//     tTstl!: string;
//     tTcco!: string;
//     tRefe!: string;
//     tCasi!: string;
//     tWmss!: number;
//     tLsta!: number;
//     tTxtn!: number;
//     tRefcntd!: number;
//     tRefcntu!: number;

// }

export class Twhinh220 {
   // id!: number;
    toorg!: number;
    torno!: string;
    tpono!: number;
    tseqn!: number;
    toset!: number;
    tcwar!: string;
    tcomp!: number;
    tacvt!: number;
    titem!: string;
    tserl!: string;
    tssts!: number;
    tlsel!: number;
    tclot!: string;
    teffn!: number;
    trevi!: string;
    tprio!: number;
    tooro!: number;
    torun!: string;
    tubin!: number;
    thstq!: number;
    tqord!: number;
    tqadv!: number;
    tqrel!: number;
    tqpic!: number;
    tqapr!: number;
    tqrej!: number;
    tqnse!: number;
    tqnsh!: number;
    tqshp!: number;
    tqoor!: number;
    tqova!: number;
    tqovd!: number;
    tqcnl!: number;
    tpddt!: Date;
    tprdt!: Date;
    taddt!: Date;
    tinup!: number;
    tbflh!: number;
    trush!: number;
    tcdck!: number;
    tqreq!: number;
    tqcad!: number;
    tqact!: number;
    tshrt!: number;
    tblck!: number;
    tcncl!: number;
    tbcko!: number;
    tpkdf!: string;
    tiubw!: number;
    tgefo!: number;
    tfmor!: string;
    tfmln!: number;
    tovlp!: number;
    tuwop!: number;
    torpr!: number;
    tocur!: string;
    tcsvl!: number;
    tcsvc!: string;
    tfprj!: string;
    tfspa!: string;
    tfact!: string;
    tfstl!: string;
    tfcco!: string;
    ttprj!: string;
    ttspa!: string;
    ttact!: string;
    ttstl!: string;
    ttcco!: string;
    trefe!: string;
    tcasi!: string;
    twmss!: number;
    tlsta!: number;
    ttxtn!: number;
    trefcntd!: number;
    trefcntu!: number;

}
